use serde::{Deserialize, Serialize};

use crate::requests::Request;
use crate::{BuildTargetIdentifier, OtherData, StatusCode};

/*
NOTE THAT:
Response has error field defined as follows:
error: JSON-RPC code and message set in case an exception happens during the request.
*/

#[derive(Debug)]
pub struct BuildTargetCompile {}

impl Request for BuildTargetCompile {
    type Params = CompileParams;
    type Result = CompileResult;
    const METHOD: &'static str = "buildTarget/compile";
}

#[derive(Debug, PartialEq, Serialize, Deserialize, Default, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CompileParams {
    /** A sequence of build targets to compile. */
    pub targets: Vec<BuildTargetIdentifier>,

    /** A unique identifier generated by the client to identify this request.
     * The server may include this id in triggered notifications or responses. */
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin_id: Option<String>,

    /** Optional arguments to the compilation process. */
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub arguments: Vec<String>,
}

#[derive(Debug, PartialEq, Serialize, Deserialize, Default, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CompileResult {
    /** An optional request id to know the origin of this report. */
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin_id: Option<String>,

    /** A status code for the execution. */
    pub status_code: StatusCode,

    /** A field containing language-specific information, like products
    of compilation or compiler-specific metadata the client needs to know. */
    #[serde(flatten, skip_serializing_if = "Option::is_none")]
    pub data: Option<CompileResultData>,
}

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case", tag = "dataKind", content = "data")]
pub enum NamedCompileResultData {}

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompileResultData {
    Named(NamedCompileResultData),
    Other(OtherData),
}

impl CompileResultData {}

#[cfg(test)]
mod tests {
    use insta::assert_json_snapshot;

    use crate::tests::test_deserialization;

    use super::*;

    #[test]
    fn compile_method() {
        assert_eq!(BuildTargetCompile::METHOD, "buildTarget/compile");
    }

    #[test]
    fn compile_params() {
        let test_data = CompileParams {
            targets: vec![BuildTargetIdentifier::default()],
            origin_id: Some("test_message".to_string()),
            arguments: vec!["test_argument".to_string()],
        };

        test_deserialization(
            r#"{"targets":[{"uri":""}],"originId":"test_message","arguments":["test_argument"]}"#,
            &test_data,
        );

        test_deserialization(r#"{"targets":[]}"#, &CompileParams::default());
    }

    #[test]
    fn compile_result() {
        let test_data = CompileResult {
            origin_id: Some("test_message".to_string()),
            status_code: StatusCode::default(),
            data: Some(CompileResultData::Other(OtherData {
                data_kind: "test_dataKind".to_string(),
                data: serde_json::json!({"dataKey": "dataValue"}),
            })),
        };

        assert_json_snapshot!(test_data,
            @r#"
        {
          "originId": "test_message",
          "statusCode": 2,
          "dataKind": "test_dataKind",
          "data": {
            "dataKey": "dataValue"
          }
        }
        "#
        );
        assert_json_snapshot!(CompileResult::default(),
            @r#"
        {
          "statusCode": 2
        }
        "#
        );
    }
}
