[package]
name = "cargo-bsp"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.147"
serde_json = "1.0.89"
serde_repr = "0.1.9"
lsp-types = "0.94.0"
crossbeam-channel = "0.5.6"
rustc-hash = "1.1.0"
anyhow = {version = "1.0.69", default-features = false}
url = "2.3.1"
