[package]
name = "cargo-bsp"
version = "0.1.0"
edition = "2021"
default-run = "cargo-bsp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonrpsee-types = "0.16.0"
