use serde::{Deserialize, Serialize};

use crate::*;

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskProgressParams {
    /// Unique id of the task with optional reference to parent task id
    pub task_id: TaskId,
    /// A unique identifier generated by the client to identify this request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin_id: Option<Identifier>,
    /// Timestamp of when the event started in milliseconds since Epoch.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_time: Option<i64>,
    /// Message describing the task.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// If known, total amount of work units in this task.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    /// If known, completed amount of work units in this task.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress: Option<i64>,
    /// Name of a work unit. For example, "files" or "tests". May be empty.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    /// Optional metadata about the task.
    /// Objects for specific tasks like compile, test, etc are specified in the protocol.
    #[serde(flatten, skip_serializing_if = "Option::is_none")]
    pub data: Option<TaskProgressData>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use insta::assert_json_snapshot;

    #[test]
    fn task_progress_params() {
        let test_data = TaskProgressParams {
            task_id: TaskId::default(),
            origin_id: Some(Identifier::default()),
            event_time: Some(1),
            message: Some("test_message".to_string()),
            total: Some(2),
            progress: Some(3),
            unit: Some("test_unit".to_string()),
            data: Some(TaskProgressData::Other(OtherData {
                data_kind: "test_dataKind".to_string(),
                data: serde_json::json!({"dataKey": "dataValue"}),
            })),
        };

        assert_json_snapshot!(test_data,
            @r#"
        {
          "taskId": {
            "id": ""
          },
          "originId": "",
          "eventTime": 1,
          "message": "test_message",
          "total": 2,
          "progress": 3,
          "unit": "test_unit",
          "dataKind": "test_dataKind",
          "data": {
            "dataKey": "dataValue"
          }
        }
        "#
        );
        assert_json_snapshot!(TaskProgressParams::default(),
            @r#"
        {
          "taskId": {
            "id": ""
          }
        }
        "#
        );
    }
}
