[package]
name = "bsp4rs"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
cargo_metadata = "0.17.0"
lsp-types = "0.94.0"
serde = "1.0.147"
serde_json = "1.0.89"
serde_repr = "0.1.9"

[dev-dependencies]
insta = { version = "1.31.0", features = ["yaml", "json"] }
url = "2.3.1"
