name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Basic verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all
      - name: Check rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Check Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
